# Generated by Django 2.2.6 on 2019-11-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoDisciplina',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dataIn', models.DateField()),
                ('dataFi', models.DateField()),
                ('codDisciplina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Disciplina')),
                ('codProfessor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cadastros.Professor')),
            ],
        ),
    ]
