# Generated by Django 2.2.6 on 2019-11-27 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cadastros', '0002_historicodisciplina'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='codMatricula',
        ),
        migrations.DeleteModel(
            name='Frequencia',
        ),
        migrations.DeleteModel(
            name='Nota',
        ),
    ]
